# Generated by Django 5.0.4 on 2024-05-09 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_cargo', '0006_rename_car_id_cartypebody_car_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='notifyCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_first_user', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], default='y', max_length=1)),
                ('status_second_user', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], default='u', max_length=1)),
                ('comment_first_user', models.TextField(null=True)),
                ('comment_second_user', models.TextField(null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_cargo.car')),
                ('first_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_user_notify', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user_notify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notify_car',
            },
        ),
        migrations.CreateModel(
            name='notifyCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_first_user', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], default='y', max_length=1)),
                ('status_second_user', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], default='u', max_length=1)),
                ('comment_first_user', models.TextField(null=True)),
                ('comment_second_user', models.TextField(null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_cargo.cargo')),
                ('first_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_user_cargo_notify', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user_cargo_notify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notify_cargo',
            },
        ),
    ]
