# Generated by Django 5.0.4 on 2024-04-25 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_cargo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='typeBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'db_table': 'type_body',
            },
        ),
        migrations.CreateModel(
            name='typeLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='type_body',
        ),
        migrations.RemoveField(
            model_name='car',
            name='type_loading',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='id_user',
        ),
        migrations.AddField(
            model_name='car',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='carTypeBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_cargo.car')),
                ('type_body_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_cargo.typebody')),
            ],
            options={
                'db_table': 'car_type_body',
            },
        ),
        migrations.CreateModel(
            name='carTypeLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_cargo.car')),
                ('type_loading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_cargo.typeloading')),
            ],
            options={
                'db_table': 'car_type_loading',
            },
        ),
    ]
