# Generated by Django 5.0.4 on 2024-04-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_cargo', '0002_typebody_typeloading_remove_car_type_body_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typeloading',
            table='type_loading',
        ),
    ]
