# Generated by Django 5.0.4 on 2024-04-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_cargo', '0003_alter_typeloading_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='user',
            new_name='user_id',
        ),
    ]
