# Generated by Django 5.0.4 on 2024-04-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_cargo', '0004_rename_user_cargo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='user_id',
            new_name='user',
        ),
    ]
