# Generated by Django 5.0.4 on 2024-04-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_cargo', '0005_rename_user_id_car_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartypebody',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='cartypebody',
            old_name='type_body_id',
            new_name='type_body',
        ),
        migrations.RenameField(
            model_name='cartypeloading',
            old_name='car_id',
            new_name='car',
        ),
    ]
